import { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext(null);

export const SUPPORTED_LANGUAGES = [
  { code: "en", label: "English" },
  { code: "ta", label: "தமிழ் (Tamil)" },
  { code: "hi", label: "हिन्दी (Hindi)" },
  { code: "te", label: "తెలుగు (Telugu)" },
  { code: "ml", label: "മലയാളം (Malayalam)" },
  { code: "kn", label: "ಕನ್ನಡ (Kannada)" },
  { code: "bn", label: "বাংলা (Bengali)" },
  { code: "mr", label: "मराठी (Marathi)" },
];

export const VOCABULARY = {
  ta: {
    "Physics": "இயற்பியல்",
    "Chemistry": "வேதியியல்",
    "Biology": "உயிரியல்",
    "Mathematics": "கணிதம்",
    "Maths": "கணிதம்",
    "Operating Systems": "இயக்க முறைமைகள்",
    "Operating System": "இயக்க முறைமை",
    "Computer Networks": "கணினி நெட்வொர்க்குகள்",
    "Algorithms": "அல்காரிதம்கள்",
    "Data Structures": "தரவு கட்டமைப்புகள்",
    "Theory of Computation": "கணினி அறிவியல் கோட்பாடு",
    "Compiler Design": "தொகுப்பி வடிவமைப்பு",
    "Computer Organization": "கணினி அமைப்பு",
    "Database System": "தரவுத்தள அமைப்பு",
    "Databases": "தரவுத்தளங்கள்",
    "Database": "தரவுத்தளம்",
    "Digital Logic": "டிஜிட்டல் லாஜிக்",
    "General Aptitude": "பொது திறனறிவு",
    "Engineering Mathematics": "பொறியியல் கணிதம்",
    "Aptitude": "திறனறிவு",
    "Reasoning": "பகுத்தறிவு",
    "Indian Polity": "இந்திய அரசியல்",
    "Software Engineering": "மென்பொருள் பொறியியல்",
    "Science": "அறிவியல்",
    "Reference Book": "குறிப்பு நூல்",
    "Practice Workbook": "பயிற்சி கையேடு",
    "Previous Year Papers": "முந்தைய ஆண்டு வினாத்தாள்கள்",
    "Revision Guide": "மறுபரிசீலனை வழிகாட்டி",
    "Test Series": "தேர்வுத் தொடர்",
    "Flashcard Deck": "நினைவூட்டல் அட்டைத் தொகுப்பு",
    "Textbook": "பாடநூல்",
    "Handbook": "கையேடு",
    "Edition": "பதிப்பு",
    "Print": "அச்சு",
    "Concepts": "கோட்பாடுகள்",
    "Principles": "கோட்பாடுகள்",
  },
  hi: {
    "Physics": "भौतिकी",
    "Chemistry": "रसायन विज्ञान",
    "Biology": "जीव विज्ञान",
    "Mathematics": "गणित",
    "Maths": "गणित",
    "Operating Systems": "ऑपरेटिंग सिस्टम",
    "Operating System": "ऑपरेटिंग सिस्टम",
    "Computer Networks": "कंप्यूटर नेटवर्क",
    "Algorithms": "एल्गोरिदम",
    "Data Structures": "डेटा संरचनाएं",
    "Theory of Computation": "कंप्यूटर विज्ञान सिद्धांत",
    "Compiler Design": "कंपाइलर डिज़ाइन",
    "Computer Organization": "कंप्यूटर संगठन",
    "Database System": "डेटाबेस सिस्टम",
    "Databases": "डेटाबेस",
    "Database": "डेटाबेस",
    "Digital Logic": "डिजिटल लॉजिक",
    "General Aptitude": "सामान्य योग्यता",
    "Engineering Mathematics": "इंजीनियरिंग गणित",
    "Aptitude": "योग्यता",
    "Reasoning": "तर्कशक्ति",
    "Indian Polity": "भारतीय राजव्यवस्था",
    "Software Engineering": "सॉफ्टवेयर इंजीनियरिंग",
    "Science": "विज्ञान",
    "Reference Book": "संदर्भ पुस्तक",
    "Practice Workbook": "अभ्यास कार्यपुस्तिका",
    "Previous Year Papers": "पिछले वर्षों के प्रश्न पत्र",
    "Revision Guide": "रिवीजन गाइड",
    "Test Series": "टेस्ट सीरीज़",
    "Flashcard Deck": "फ्लैशकार्ड सेट",
    "Textbook": "पाठ्यपुस्तक",
    "Handbook": "हस्तपुस्तिका",
    "Edition": "संस्करण",
    "Print": "प्रिंट",
    "Concepts": "सिद्धांत",
    "Principles": "सिद्धांत",
  },
  te: {
    "Physics": "భౌతికశాస్త్రం",
    "Chemistry": "రసాయన శాస్త్రం",
    "Biology": "జీవశాస్త్రం",
    "Mathematics": "గణితం",
    "Maths": "గణితం",
    "Operating Systems": "ఆపరేటింగ్ సిస్టమ్స్",
    "Operating System": "ఆపరేటింగ్ సిస్టమ్",
    "Computer Networks": "కంప్యూటర్ నెట్‌వర్క్‌లు",
    "Algorithms": "అల్గారిథమ్స్",
    "Data Structures": "డేటా స్ట్రక్చర్స్",
    "Theory of Computation": "కంప్యూటర్ థియరీ",
    "Compiler Design": "కంపైలర్ డిజైన్",
    "Computer Organization": "కంప్యూటర్ ఆర్గనైజేషన్",
    "Databases": "డేటాబేస్",
    "Database": "డేటాబేస్",
    "Digital Logic": "డిజిటల్ లాజిక్",
    "General Aptitude": "జనరల్ ఆప్టిట్యూడ్",
    "Engineering Mathematics": "ఇంజనీరింగ్ గణితం",
    "Aptitude": "ఆప్టిట్యూడ్",
    "Reasoning": "రీజనింగ్",
    "Reference Book": "రిఫరెన్స్ పుస్తకం",
    "Practice Workbook": "ప్రాక్టీస్ వర్క్‌బుక్",
    "Previous Year Papers": "మునుపటి సంవత్సరం పేపర్లు",
    "Revision Guide": "రివిజన్ గైడ్",
    "Edition": "ఎడిషన్",
  },
  ml: {
    "Physics": "ഭൗതികശാസ്ത്രം",
    "Chemistry": "രസതന്ത്രം",
    "Biology": "ജീവശാസ്ത്രം",
    "Mathematics": "ഗണിതം",
    "Operating Systems": "ഓപ്പറേറ്റിംഗ് സിസ്റ്റം",
    "Computer Networks": "കമ്പ്യൂട്ടർ നെറ്റ്‌വർക്കുകൾ",
    "Algorithms": "അൽഗോരിതങ്ങൾ",
    "Data Structures": "ഡാറ്റാ ഘടനകൾ",
    "Databases": "ഡാറ്റാബേസ്",
    "General Aptitude": "ജനറൽ ആപ്റ്റിറ്റ്യൂഡ്",
    "Engineering Mathematics": "എഞ്ചിനീയറിംഗ് മാത്തമാറ്റിക്സ്",
    "Reference Book": "റഫറൻസ് പുസ്തകം",
    "Practice Workbook": "പ്രാക്ടീസ് വർക്ക്ബുക്ക്",
    "Previous Year Papers": "മുൻ വർഷത്തെ പേപ്പറുകൾ",
    "Revision Guide": "റിവിഷൻ ഗൈഡ്",
    "Edition": "പതിപ്പ്",
  },
  kn: {
    "Physics": "ಭೌತಶಾಸ್ತ್ರ",
    "Chemistry": "ರಸಾಯನಶಾಸ್ತ್ರ",
    "Biology": "ಜೀವಶಾಸ್ತ್ರ",
    "Mathematics": "ಗಣಿತ",
    "Operating Systems": "ಆಪರೇಟಿಂಗ್ ಸಿಸ್ಟಮ್ಸ್",
    "Computer Networks": "ಕಂಪ್ಯೂಟರ್ ನೆಟ್‌ವರ್ಕ್‌ಗಳು",
    "Algorithms": "ಅಲ್ಗಾರಿದಮ್‌ಗಳು",
    "Data Structures": "ಡೇಟಾ ರಚನೆಗಳು",
    "Databases": "ಡೇಟಾಬೇಸ್",
    "General Aptitude": "ಜನರಲ್ ಆಪ್ಟಿಟ್ಯೂಡ್",
    "Engineering Mathematics": "ಇಂಜಿನಿಯರಿಂಗ್ ಗಣಿತ",
    "Reference Book": "ಉಲ್ಲೇಖ ಪುಸ್ತಕ",
    "Practice Workbook": "ಅಭ್ಯಾಸ ಪುಸ್ತಕ",
    "Previous Year Papers": "ಹಿಂದಿನ ವರ್ಷದ ಪತ್ರಿಕೆಗಳು",
    "Revision Guide": "ಪರಿಷ್ಕರಣೆ ಮಾರ್ಗದರ್ಶಿ",
    "Edition": "ಆವೃತ್ತಿ",
  },
  bn: {
    "Physics": "পদার্থবিজ্ঞান",
    "Chemistry": "রসায়ন",
    "Biology": "জীববিজ্ঞান",
    "Mathematics": "গণিত",
    "Operating Systems": "অপারেটিং সিস্টেম",
    "Computer Networks": "কম্পিউটার নেটওয়ার্ক",
    "Algorithms": "অ্যালগরিদম",
    "Data Structures": "ডেটা কাঠামো",
    "Databases": "ডাটাবেস",
    "General Aptitude": "সাধারণ যোগ্যতা",
    "Engineering Mathematics": "প্রকৌশল গণিত",
    "Reference Book": "রেফারেন্স বই",
    "Practice Workbook": "অনুশীলন পুস্তিকা",
    "Previous Year Papers": "বিগত বছরের প্রশ্নপত্র",
    "Revision Guide": "রিভিশন গাইড",
    "Edition": "সংস্করণ",
  },
  mr: {
    "Physics": "भौतिकशास्त्र",
    "Chemistry": "रसायनशास्त्र",
    "Biology": "जीवशास्त्र",
    "Mathematics": "गणित",
    "Operating Systems": "ऑपरेटिंग सिस्टम",
    "Computer Networks": "संगणक नेटवर्क",
    "Algorithms": "अल्गोरिदम",
    "Data Structures": "डेटा स्ट्रक्चर्स",
    "Databases": "डेटाबेस",
    "General Aptitude": "सामान्य अभियोग्यता",
    "Engineering Mathematics": "अभियांत्रिकी गणित",
    "Reference Book": "संदर्भ पुस्तक",
    "Practice Workbook": "सराव कार्यपुस्तिका",
    "Previous Year Papers": "मागील वर्षांचे पेपर्स",
    "Revision Guide": "उजळणी मार्गदर्शक",
    "Edition": "आवृत्ती",
  },
};

export const BOOK_TRANSLATIONS = {
  ta: {
    "Operating System Concepts": "இயக்க முறைமை கோட்பாடுகள்",
    "Computer Networks": "கணினி நெட்வொர்க்குகள்",
    "Computer Networking: A Top-Down Approach": "கணினி நெட்வொர்க்கிங்: மேல்-கீழ் அணுகுமுறை",
    "Introduction to Algorithms": "அல்காரிதம்களின் அறிமுகம்",
    "Database System Concepts": "தரவுத்தள அமைப்பு கோட்பாடுகள்",
    "Higher Engineering Mathematics": "உயர் பொறியியல் கணிதம்",
    "Theory of Computer Science": "கணினி அறிவியல் கோட்பாடு",
    "Discrete Mathematics and its Applications": "தனித்துவ கணிதம் மற்றும் பயன்பாடுகள்",
    "Computer Organization and Architecture": "கணினி அமைப்பு மற்றும் கட்டமைப்பு",
    "Compilers: Principles, Techniques, and Tools": "தொகுப்பிகள்: கோட்பாடுகள் மற்றும் நுட்பங்கள்",
    "Digital Logic and Computer Design": "டிஜிட்டல் லாஜிக் மற்றும் கணினி வடிவமைப்பு",
    "Quantitative Aptitude for Competitive Examinations": "போட்டித் தேர்வுகளுக்கான கணித திறனறிவு",
    "NCERT Biology Class 11 & 12": "என்சிஇஆர்டி உயிரியல் வகுப்பு 11 & 12",
    "Concepts of Physics": "இயற்பியல் கோட்பாடுகள்",
    "Concepts of Physics, Volume 1": "இயற்பியல் கோட்பாடுகள், தொகுதி 1",
    "Concepts of Physics, Volume 2": "இயற்பியல் கோட்பாடுகள், தொகுதி 2",
    "Problems in General Physics": "பொது இயற்பியல் வினாக்கள் மற்றும் தீர்வுகள்",
    "Trueman's Elementary Biology, Volume 1": "ட்ரூமேனின் அடிப்படை உயிரியல், தொகுதி 1",
    "Trueman's Elementary Biology, Volume 2": "ட்ரூமேனின் அடிப்படை உயிரியல், தொகுதி 2",
    "Indian Polity": "இந்திய அரசியல் அமைப்பு",
    "Certificate Physical and Human Geography": "இயற்கை மற்றும் மனித புவியியல்",
    "How to Prepare for Quantitative Aptitude for CAT": "CAT கணித திறனறிவுக்கு தயாராவது எப்படி",
    "How to Prepare for Verbal Ability and Reading Comprehension for CAT": "CAT வாய்மொழி திறன் மற்றும் வாசிப்பு புரிதலுக்கு தயாராவது எப்படி",
    "Universal's Guide to CLAT & LLB Entrance Examination": "CLAT மற்றும் LLB நுழைவுத் தேர்வுக்கான வழிகாட்டி",
    "Child Development and Pedagogy for CTET and TETs": "குழந்தை மேம்பாடு மற்றும் கற்பித்தல் முறை",
    "A Modern Approach to Verbal & Non-Verbal Reasoning": "வாய்மொழி மற்றும் வாய்மொழியற்ற நவீன பகுத்தறிவு",
    "Lucent's General Knowledge": "லூசென்ட் பொது அறிவு கையேடு",
    "Arihant TNPSC Group IV Combined Civil Services Examination": "அரிஹந்த் TNPSC குரூப் 4 ஒருங்கிணைந்த குடிமைப்பணிகள் தேர்வு",
    "Fast Track Objective Arithmetic": "விரைவு குறிக்கோள் अंकகணிதம்",
    "Software Engineering": "மென்பொருள் பொறியியல்",
  },
  hi: {
    "Operating System Concepts": "ऑपरेटिंग सिस्टम सिद्धांत (Operating System Concepts - Silberschatz)",
    "Computer Networks": "कंप्यूटर नेटवर्क (Computer Networks - Tanenbaum)",
    "Introduction to Algorithms": "एल्गोरिदम का परिचय (CLRS Algorithms)",
    "Database System Concepts": "डेटाबेस सिस्टम सिद्धांत (Database Concepts - Korth)",
    "Higher Engineering Mathematics": "उच्च इंजीनियरिंग गणित (Higher Engineering Mathematics - Grewal)",
    "Theory of Computer Science": "कंप्यूटर विज्ञान सिद्धांत (Automata & Computation - Mishra)",
    "Discrete Mathematics and its Applications": "असतत गणित और इसके अनुप्रयोग (Discrete Mathematics - Rosen)",
    "Computer Organization and Architecture": "कंप्यूटर संगठन और वास्तुकला (Computer Architecture - Stallings)",
    "Compilers: Principles, Techniques, and Tools": "कंपाइलर: सिद्धांत, तकनीक और उपकरण (Dragon Book - Aho)",
    "Digital Logic and Computer Design": "डिजिटल लॉजिक और कंप्यूटर डिजाइन (Morris Mano)",
    "Quantitative Aptitude for Competitive Examinations": "प्रतियोगी परीक्षाओं के लिए मात्रात्मक योग्यता (R.S. Aggarwal)",
    "NCERT Biology Class 11 & 12": "एनसीईआरटी जीव विज्ञान कक्षा 11 और 12 (NCERT Biology)",
    "Concepts of Physics": "भौतिकी की अवधारणाएँ (Concepts of Physics - H.C. Verma)",
    "Indian Polity": "भारतीय राजव्यवस्था (Indian Polity - M. Laxmikanth)",
    "A Modern Approach to Verbal & Non-Verbal Reasoning": "मौखिक और गैर-मौखिक तर्क (R.S. Aggarwal)",
    "Software Engineering": "सॉफ्टवेयर इंजीनियरिंग (Roger Pressman)",
  },
  te: {
    "Operating System Concepts": "ఆపరేటింగ్ సిస్టమ్ కాన్సెప్ట్స్ (Operating System Concepts - Silberschatz)",
    "Computer Networks": "కంప్యూటర్ నెట్‌వర్క్‌లు (Computer Networks - Tanenbaum)",
    "Introduction to Algorithms": "అల్గారిథమ్స్ పరిచయం (CLRS Algorithms)",
    "Database System Concepts": "డేటాబేస్ సిస్టమ్ కాన్సెప్ట్స్ (Database Concepts - Korth)",
    "Higher Engineering Mathematics": "హయ్యర్ ఇంజనీరింగ్ గణితం (Higher Engineering Mathematics - Grewal)",
    "Quantitative Aptitude for Competitive Examinations": "పోటీ పరీక్షల కొరకు క్వాంటిటేటివ్ ఆప్టిట్యూడ్ (R.S. Aggarwal)",
    "Concepts of Physics": "భౌతికశాస్త్ర భావనలు (Concepts of Physics - H.C. Verma)",
    "Indian Polity": "భారతీయ రాజ్యాంగం (Indian Polity - M. Laxmikanth)",
  },
  ml: {
    "Operating System Concepts": "ഓപ്പറേറ്റിംഗ് സിസ്റ്റം ആശയങ്ങൾ (Operating System Concepts - Silberschatz)",
    "Computer Networks": "കമ്പ്യൂട്ടർ നെറ്റ്‌വർക്കുകൾ (Computer Networks - Tanenbaum)",
    "Introduction to Algorithms": "അൽഗോരിതങ്ങളുടെ ആമുഖം (CLRS Algorithms)",
    "Database System Concepts": "ഡാറ്റാബേസ് സിസ്റ്റം ആശയങ്ങൾ (Database Concepts - Korth)",
    "Higher Engineering Mathematics": "ഹയർ എഞ്ചിനീയറിംഗ് മാത്തമാറ്റിക്സ് (Higher Engineering Mathematics - Grewal)",
    "Quantitative Aptitude for Competitive Examinations": "ക്വാണ്ടിറ്റേറ്റീവ് ആപ്റ്റിറ്റ്യൂഡ് (R.S. Aggarwal)",
    "Concepts of Physics": "ഭൗതികശാസ്ത്ര തത്വങ്ങൾ (H.C. Verma)",
  },
  kn: {
    "Operating System Concepts": "ಆಪರೇಟಿಂಗ್ ಸಿಸ್ಟಮ್ ಕಾನ್ಸೆಪ್ಟ್ಸ್ (Operating System Concepts - Silberschatz)",
    "Computer Networks": "ಕಂಪ್ಯೂಟರ್ ನೆಟ್‌ವರ್ಕ್‌ಗಳು (Computer Networks - Tanenbaum)",
    "Introduction to Algorithms": "ಅಲ್ಗಾರಿದಮ್‌ಗಳ ಪರಿಚಯ (CLRS Algorithms)",
    "Database System Concepts": "ಡೇಟಾಬೇಸ್ ಸಿಸ್ಟಮ್ ಕಾನ್ಸೆಪ್ಟ್ಸ್ (Database Concepts - Korth)",
    "Higher Engineering Mathematics": "ಹೈಯರ್ ಇಂಜಿನಿಯರಿಂಗ್ ಗಣಿತ (Higher Engineering Mathematics - Grewal)",
    "Quantitative Aptitude for Competitive Examinations": "ಕ್ವಾಂಟಿಟೇಟಿವ್ ಆಪ್ಟಿಟ್ಯೂಡ್ (R.S. Aggarwal)",
    "Concepts of Physics": "ಭೌತಶಾಸ್ತ್ರದ ಪರಿಕಲ್ಪನೆಗಳು (H.C. Verma)",
  },
  bn: {
    "Operating System Concepts": "অপারেটিং সিস্টেম ধারণা (Operating System Concepts - Silberschatz)",
    "Computer Networks": "কম্পিউটার নেটওয়ার্ক (Computer Networks - Tanenbaum)",
    "Introduction to Algorithms": "অ্যালগরিদমের ভূমিকা (CLRS Algorithms)",
    "Database System Concepts": "ডাটাবেস সিস্টেম ধারণা (Database Concepts - Korth)",
    "Higher Engineering Mathematics": "উচ্চতর প্রকৌশল গণিত (Higher Engineering Mathematics - Grewal)",
    "Quantitative Aptitude for Competitive Examinations": "প্রতিযোগিতামূলক পরীক্ষার জন্য গণিত (R.S. Aggarwal)",
    "Concepts of Physics": "পদার্থবিজ্ঞানের ধারণা (H.C. Verma)",
  },
  mr: {
    "Operating System Concepts": "ऑपरेटिंग सिस्टम संकल्पना (Operating System Concepts - Silberschatz)",
    "Computer Networks": "संगणक नेटवर्क (Computer Networks - Tanenbaum)",
    "Introduction to Algorithms": "अल्गोरिदमचा परिचय (CLRS Algorithms)",
    "Database System Concepts": "डेटाबेस सिस्टम संकल्पना (Database Concepts - Korth)",
    "Higher Engineering Mathematics": "उच्च अभियांत्रिकी गणित (Higher Engineering Mathematics - Grewal)",
    "Quantitative Aptitude for Competitive Examinations": "संख्यात्मक अभियोग्यता (R.S. Aggarwal)",
    "Concepts of Physics": "भौतिकशास्त्राच्या संकल्पना (H.C. Verma)",
  },
};

export const TRANSLATIONS = {
  en: {
    exams: "Exams",
    myProgress: "My Progress",
    myProgressSub: "Track consistency across your registered exams, subjects, mock tests, and daily revision.",
    marketplace: "Marketplace",
    marketplaceSub: "Buy textbooks, claim free student-donated materials, sell completed books, or donate to aspirants.",
    ordersTracking: "Orders & Tracking",
    resources: "Resources",
    community: "Community",
    studyPlanner: "Study Planner",
    settings: "Settings",
    adminDashboard: "Admin Dashboard",
    deliveryDashboard: "Delivery Dashboard",
    dashboard: "Dashboard",
    manageExams: "Manage Exams",
    manageResources: "Manage Resources",
    manageProducts: "Marketplace",
    users: "Users",
    orders: "Orders",
    returns: "Returns / Resale / Donations",
    communications: "Communication Logs",
    logOut: "Log out",
    language: "Language",
    signIn: "Sign In",
    search: "Search",
    filter: "Filter",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    submit: "Submit",
    next: "Next",
    previous: "Previous",
    close: "Close",
    loading: "Loading…",
    registeredExams: "Registered Exams",
    unregisteredExams: "Unregistered Exams",
    syllabus: "Syllabus & Mock Tests",
    studyHeatmap: "Study Heatmap",
    analytics: "Analytics & Progress Graphs",
    flashcards: "Flashcards",
    notes: "Notes",
    quizGenerator: "Quiz Generator",
    generateQuiz: "Generate Quiz",
    fromTopic: "From Syllabus Topic",
    fromNotes: "Upload & Generate from Notes",
    topicOrSubject: "Syllabus Subject / Specific Topic",
    numberOfQuestions: "Number of Questions",
    notesContent: "Notes Text (Pasted or Auto-loaded from Upload)",
    reset: "Reset",
    start: "Start",
    complete: "Complete",
    quiz: "Quiz",
    analysis: "Analysis",
    overallProgress: "Overall Progress",
    topicsCompleted: "topics complete",
    currentStreak: "Current streak",
    longestStreak: "Longest",
    buyBooks: "Buy Books",
    freeDonatedBooks: "Free Donated Books (₹0)",
    myBooksForSale: "My Books for Sale",
    myDonatedBooks: "My Donated Books",
    sellOrDonate: "Sell or Donate a Book",
    pdfsAndNotes: "PDFs & Shared Material",
    cart: "Cart",
    yourCart: "Your Cart",
    cartEmpty: "Your cart is empty.",
    remove: "Remove",
    total: "Total",
    proceedToCheckout: "Proceed to checkout",
    searchBooks: "Search books by title, author, or subject…",
    addToCart: "Add to Cart",
    subjectMockTests: "Subject Mock Tests & Full CBT Links",
    analyticsOverview: "Performance Analytics & Progress Graphs",
    studentId: "Student ID",
    changePassword: "Change Password",
    fontSize: "Font Size",
    unregisterExam: "Remove / Unregister",
    enterMarks: "Enter Marks",
    marksLogged: "Marks Logged",
    takeMockTest: "Take Mock Test",
    score: "Score",
    outOf: "Out of",
    saveMarks: "Save Score",
    allSubjects: "All Subjects",
    assignedDeliveries: "Assigned Deliveries",
    pickedUp: "Picked Up",
    inTransit: "In Transit",
    delivered: "Delivered",
    updateStatus: "Update Status",
    deliveryAddress: "Delivery Address",
    customer: "Student",
    pickupDonation: "Pickup Donation",
    trackingNumber: "Tracking ID",
    preparingForExamIntro: "Preparing for competitive exams? Leave it to us.",
  },
  ta: {
    exams: "தேர்வுகள்",
    myProgress: "எனது முன்னேற்றம்",
    myProgressSub: "உங்கள் தேர்வுகள், பாடங்கள், போலித் தேர்வுகள் மற்றும் தினசரி திருத்தங்களை கண்காணிக்கவும்.",
    marketplace: "புத்தகச் சந்தை",
    marketplaceSub: "பாடப்புத்தகங்களை வாங்கவும், இலவச நன்கொடை புத்தகங்களைப் பெறவும், உங்கள் புத்தகங்களை விற்கவும் அல்லது தானம் செய்யவும்.",
    ordersTracking: "ஆர்டர்கள் & கண்காணிப்பு",
    resources: "கல்வி வளங்கள்",
    community: "மாணவர் சமூகம்",
    studyPlanner: "படிப்புத் திட்டம்",
    settings: "அமைப்புகள்",
    adminDashboard: "நிர்வாகக் குழு பலகை",
    deliveryDashboard: "டெலிவரி பலகை",
    dashboard: "பலகை",
    manageExams: "தேர்வுகளை நிர்வகி",
    manageResources: "வளங்களை நிர்வகி",
    manageProducts: "புத்தகச் சந்தை",
    users: "பயனர்கள்",
    orders: "ஆர்டர்கள்",
    returns: "திரும்பப் பெறுதல் & நன்கொடைகள்",
    communications: "தொடர்பு பதிவுகள்",
    logOut: "வெளியேறு",
    language: "மொழி",
    signIn: "உள்நுழைக",
    search: "தேடு",
    filter: "வடிகட்டு",
    save: "சேமி",
    cancel: "ரத்து செய்",
    delete: "நீக்கு",
    edit: "திருத்து",
    submit: "சமர்ப்பி",
    next: "அடுத்து",
    previous: "முந்தைய",
    close: "மூடு",
    loading: "ஏற்றப்படுகிறது…",
    registeredExams: "பதிவு செய்த தேர்வுகள்",
    unregisteredExams: "பிற தேர்வுகள்",
    syllabus: "பாடத்திட்டம் & போலித் தேர்வுகள்",
    studyHeatmap: "படிப்பு வரைபடம்",
    analytics: "முன்னேற்ற வரைபடங்கள் & பகுப்பாய்வு",
    flashcards: "நினைவூட்டல் அட்டைகள்",
    notes: "குறிப்புகள்",
    quizGenerator: "வினாடி வினா உருவாக்கி",
    generateQuiz: "வினாடி வினா உருவாக்கு",
    fromTopic: "பாட தலைப்பிலிருந்து",
    fromNotes: "குறிப்புகளிலிருந்து உருவாக்கு",
    topicOrSubject: "பாடப்பிரிவு / குறிப்பிட்ட தலைப்பு",
    numberOfQuestions: "கேள்விகளின் எண்ணிக்கை",
    notesContent: "குறிப்புகள் உரை (கோப்பு பதிவேற்றப்பட்டது)",
    reset: "மீட்டமை",
    start: "தொடங்கு",
    complete: "முடிந்தது",
    quiz: "வினாடி வினா",
    analysis: "பகுப்பாய்வு",
    overallProgress: "ஒட்டுமொத்த முன்னேற்றம்",
    topicsCompleted: "தலைப்புகள் முடிந்தது",
    currentStreak: "தற்போதைய தொடர்ச்சி",
    longestStreak: "நீண்ட தொடர்ச்சி",
    buyBooks: "புத்தகங்களை வாங்க",
    freeDonatedBooks: "இலவச நன்கொடை புத்தகங்கள் (₹0)",
    myBooksForSale: "நான் விற்பனைக்கு வைத்துள்ளவை",
    myDonatedBooks: "நான் தானம் செய்த புத்தகங்கள்",
    sellOrDonate: "புத்தகத்தை விற்க / தானம் செய்ய",
    pdfsAndNotes: "PDF & பகிரப்பட்ட குறிப்புகள்",
    cart: "கூடை",
    yourCart: "உங்கள் கூடை",
    cartEmpty: "கூடை காலியாக உள்ளது.",
    remove: "நீக்கு",
    total: "மொத்தம்",
    proceedToCheckout: "செக்அவுட் தொடரவும்",
    searchBooks: "புத்தகம் அல்லது ஆசிரியர் பெயர் மூலம் தேடவும்…",
    addToCart: "கூடையில் சேர்க்க",
    subjectMockTests: "பாடவாரி போலித் தேர்வுகள்",
    analyticsOverview: "முன்னேற்ற வரைபடங்கள் & பகுப்பாய்வு",
    studentId: "மாணவர் அடையாள எண் (Student ID)",
    changePassword: "கடவுச்சொல்லை மாற்றுக",
    fontSize: "எழுத்து அளவு",
    unregisterExam: "நீக்கு / பதிவு ரத்து செய்",
    enterMarks: "மதிப்பெண்களை உள்ளிடுக",
    marksLogged: "மதிப்பெண் பதிவு செய்யப்பட்டது",
    takeMockTest: "போலித் தேர்வு எடு",
    score: "மதிப்பெண்",
    outOf: "மொத்தம்",
    saveMarks: "சேமி",
    allSubjects: "அனைத்து பாடங்கள்",
    assignedDeliveries: "ஒதுக்கப்பட்ட டெலிவரிகள்",
    pickedUp: "பெறப்பட்டது",
    inTransit: "வழியில் உள்ளது",
    delivered: "டெலிவரி செய்யப்பட்டது",
    updateStatus: "நிலையை மாற்று",
    deliveryAddress: "டெலிவரி முகவரி",
    customer: "மாணவர்",
    pickupDonation: "தானத்தை பெறுக",
    trackingNumber: "கண்காணிப்பு எண்",
    preparingForExamIntro: "தேர்வுகளுக்கு தயாராகிறீர்களா? எங்களிடம் விட்டுவிடுங்கள்.",
  },
  hi: {
    exams: "परीक्षाएं",
    myProgress: "मेरी प्रगति",
    myProgressSub: "अपनी पंजीकृत परीक्षाओं, विषयों, मॉक टेस्ट और दैनिक पुनरीक्षण पर नज़र रखें।",
    marketplace: "मार्केटप्लेस",
    marketplaceSub: "किताबें खरीदें, मुफ्त दान की गई सामग्री प्राप्त करें, पुरानी किताबें बेचें या दान करें।",
    ordersTracking: "ऑर्डर और ट्रैकिंग",
    resources: "संसाधन",
    community: "कम्युनिटी",
    studyPlanner: "स्टडी प्लानर",
    settings: "सेटिंग्स",
    adminDashboard: "एडमिन डैशबोर्ड",
    deliveryDashboard: "डिलीवरी डैशबोर्ड",
    dashboard: "डैशबोर्ड",
    manageExams: "परीक्षा प्रबंधन",
    manageResources: "संसाधन प्रबंधन",
    manageProducts: "मार्केटप्लेस",
    users: "उपयोगकर्ता",
    orders: "ऑर्डर",
    returns: "रिटर्न / पुनर्विक्रय / दान",
    communications: "संचार लॉग",
    logOut: "लॉग आउट",
    language: "भाषा",
    signIn: "साइन इन",
    search: "खोजें",
    filter: "फ़िल्टर",
    save: "सहेजें",
    cancel: "रद्द करें",
    delete: "हटाएं",
    edit: "संपादित करें",
    submit: "सबमिट करें",
    next: "अगला",
    previous: "पिछला",
    close: "बंद करें",
    loading: "लोड हो रहा है…",
    registeredExams: "पंजीकृत परीक्षाएं",
    unregisteredExams: "अन्य परीक्षाएं",
    syllabus: "पाठ्यक्रम और मॉक टेस्ट",
    studyHeatmap: "स्टडी हीटमैप",
    analytics: "विश्लेषण और प्रगति ग्राफ़",
    flashcards: "फ्लैशकार्ड",
    notes: "नोट्स",
    quizGenerator: "क्विज़ जनरेटर",
    generateQuiz: "क्विज़ बनाएं",
    fromTopic: "सिलेबस विषय से",
    fromNotes: "नोट्स से बनाएं",
    topicOrSubject: "पाठ्यक्रम विषय",
    numberOfQuestions: "प्रश्नों की संख्या",
    notesContent: "नोट्स सामग्री",
    reset: "रीसेट",
    start: "शुरू करें",
    complete: "पूर्ण",
    quiz: "क्विज़",
    analysis: "विश्लेषण",
    overallProgress: "कुल प्रगति",
    topicsCompleted: "विषय पूर्ण",
    currentStreak: "सक्रिय स्ट्रीक",
    longestStreak: "सर्वोत्तम स्ट्रीक",
    buyBooks: "किताबें खरीदें",
    freeDonatedBooks: "मुफ़्त दान की गई किताबें (₹0)",
    myBooksForSale: "बिक्री के लिए मेरी किताबें",
    myDonatedBooks: "मेरी दान की गई किताबें",
    sellOrDonate: "किताब बेचें या दान करें",
    pdfsAndNotes: "पीडीएफ और अध्ययन सामग्री",
    cart: "कार्ट",
    yourCart: "आपकी कार्ट",
    cartEmpty: "आपकी कार्ट खाली है।",
    remove: "हटाएं",
    total: "कुल",
    proceedToCheckout: "चेकआउट करें",
    searchBooks: "किताबें खोजें…",
    addToCart: "कार्ट में जोड़ें",
    subjectMockTests: "विषयवार मॉक टेस्ट",
    analyticsOverview: "प्रगति और विश्लेषण ग्राफ़",
    studentId: "Student ID",
    changePassword: "पासवर्ड बदलें",
    fontSize: "फ़ॉन्ट आकार",
    unregisterExam: "हटाएं / अनरजिस्टर करें",
    enterMarks: "अंक दर्ज करें",
    marksLogged: "अंक दर्ज किए गए",
    takeMockTest: "मॉक टेस्ट लें",
    score: "अंक",
    outOf: "कुल",
    saveMarks: "सहेजें",
    allSubjects: "सभी विषय",
    assignedDeliveries: "असाइन की गई डिलीवरी",
    pickedUp: "उठाया गया",
    inTransit: "मार्ग में",
    delivered: "वितरित",
    updateStatus: "स्थिति बदलें",
    deliveryAddress: "डिलीवरी का पता",
    customer: "छात्र",
    pickupDonation: "दान पिकअप",
    trackingNumber: "ट्रैकिंग आईडी",
    preparingForExamIntro: "प्रतियोगी परीक्षा की तैयारी कर रहे हैं? हम पर छोड़ दें।",
  },
  te: {
    exams: "పరీక్షలు",
    myProgress: "నా పురోగతి",
    myProgressSub: "మీ పరీక్షలు, అంశాలు మరియు మాక్ పరీక్షలను ట్రాక్ చేయండి.",
    marketplace: "మార్కెట్‌ప్లేస్",
    marketplaceSub: "పుస్తకాలు కొనండి, ఉచిత విరాళ పుస్తకాలను పొందండి లేదా విరాళం ఇవ్వండి.",
    ordersTracking: "ఆర్డర్‌లు & ట్రాకింగ్",
    resources: "వనరులు",
    community: "కమ్యూనిటీ",
    studyPlanner: "స్టడీ ప్లానర్",
    settings: "సెట్టింగ్‌లు",
    adminDashboard: "అడ్మిన్ డ్యాష్‌బోర్డ్",
    deliveryDashboard: "డెలివరీ డ్యాష్‌బోర్డ్",
    dashboard: "డ్యాష్‌బోర్డ్",
    manageExams: "పరీక్షల నిర్వహణ",
    manageResources: "వనరుల నిర్వహణ",
    manageProducts: "మార్కెట్‌ప్లేస్",
    users: "యూజర్లు",
    orders: "ఆర్డర్లు",
    returns: "రిటర్న్స్ & విరాళాలు",
    communications: "కమ్యూనికేషన్ లాగ్‌లు",
    logOut: "లాగ్ అవుట్",
    language: "భాష",
    syllabus: "సిలబస్ & మాక్ టెస్ట్‌లు",
    studyHeatmap: "స్టడీ హీట్‌మ్యాప్",
    analytics: "విశ్లేషణ గ్రాఫ్‌లు",
    buyBooks: "పుస్తకాలు కొనండి",
    freeDonatedBooks: "ఉచిత విరాళ పుస్తకాలు (₹0)",
    myBooksForSale: "అమ్మకానికి నా పుస్తకాలు",
    myDonatedBooks: "నా విరాళ పుస్తకాలు",
    sellOrDonate: "పుస్తకం అమ్మండి / దానం చేయండి",
    cart: "కార్ట్",
    total: "మొత్తం",
    addToCart: "కార్ట్‌కు జోడించండి",
    studentId: "Student ID",
    unregisterExam: "తీసివేయి / అన్‌రిజిస్టర్",
    enterMarks: "మార్కులు నమోదు చేయండి",
    takeMockTest: "మాక్ టెస్ట్ రాయండి",
    preparingForExamIntro: "పోటీ పరీక్షలకు సిద్ధమవుతున్నారా? మాపై నమ్మకం ఉంచండి.",
  },
  ml: {
    exams: "പരീക്ഷകൾ",
    myProgress: "എന്റെ പുരോഗതി",
    marketplace: "മാർക്കറ്റ്പ്ലേസ്",
    ordersTracking: "ഓർഡറുകൾ & ട്രാക്കിംഗ്",
    resources: "വിഭവങ്ങൾ",
    community: "കമ്മ്യൂണിറ്റി",
    studyPlanner: "പഠന പ്ലാനർ",
    settings: "ക്രമീകരണങ്ങൾ",
    adminDashboard: "അഡ്മിൻ ഡാഷ്‌ബോർഡ്",
    deliveryDashboard: "ഡെലിവറി ഡാഷ്‌ബോർഡ്",
    dashboard: "ഡാഷ്‌ബോർഡ്",
    manageExams: "പരീക്ഷകളുടെ നടത്തിപ്പ്",
    manageResources: "വിഭവങ്ങളുടെ നടത്തിപ്പ്",
    manageProducts: "മാർക്കറ്റ്പ്ലേസ്",
    users: "ഉപയോക്താക്കൾ",
    orders: "ഓർഡറുകൾ",
    returns: "റിട്ടേണുകളും ദാനങ്ങളും",
    communications: "കമ്മ്യൂണിക്കേഷൻ ലോഗുകൾ",
    logOut: "ലോഗ് ഔട്ട്",
    syllabus: "സിലബസ് & മോക്ക് ടെസ്റ്റുകൾ",
    analytics: "വിശകലന ഗ്രാഫുകൾ",
    buyBooks: "പുസ്തകങ്ങൾ വാങ്ങുക",
    freeDonatedBooks: "സൗജന്യ പുസ്തകങ്ങൾ (₹0)",
    myBooksForSale: "വിൽക്കാനുള്ള പുസ്തകങ്ങൾ",
    myDonatedBooks: "ദാനം ചെയ്ത പുസ്തകങ്ങൾ",
    sellOrDonate: "പുസ്തകം വിൽക്കുക / ദാനം ചെയ്യുക",
    cart: "കാർട്ട്",
    total: "ആകെ",
    addToCart: "കാർട്ടിലേക്ക് ചേർക്കുക",
    studentId: "Student ID",
    unregisterExam: "നീക്കം ചെയ്യുക",
    enterMarks: "മാർക്കുകൾ ചേർക്കുക",
    takeMockTest: "മോക്ക് ടെസ്റ്റ് എഴുതുക",
    preparingForExamIntro: "പരീക്ഷകൾക്കായി തയ്യാറെടുക്കുകയാണോ? ഞങ്ങളെ വിശ്വസിക്കൂ.",
  },
  kn: {
    exams: "ಪರೀಕ್ಷೆಗಳು",
    myProgress: "ನನ್ನ ಪ್ರಗತಿ",
    marketplace: "ಮಾರ್ಕೆಟ್‌ಪ್ಲೇಸ್",
    ordersTracking: "ಆರ್ಡರ್‌ಗಳು ಮತ್ತು ಟ್ರ್ಯಾಕಿಂಗ್",
    resources: "ಸಂಪನ್ಮೂಲಗಳು",
    community: "ಸಮುದಾಯ",
    studyPlanner: "ಸ್ಟಡಿ ಪ್ಲಾನರ್",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    adminDashboard: "ಅಡ್ಮಿನ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    deliveryDashboard: "ಡೆಲಿವರಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    manageExams: "ಪರೀಕ್ಷಾ ನಿರ್ವಹಣೆ",
    manageResources: "ಸಂಪನ್ಮೂಲ ನಿರ್ವಹಣೆ",
    manageProducts: "ಮಾರ್ಕೆಟ್‌ಪ್ಲೇಸ್",
    users: "ಬಳಕೆದಾರರು",
    orders: "ಆರ್ಡರ್‌ಗಳು",
    returns: "ಹಿಂತಿರುಗಿಸುವಿಕೆ & ದಾನ",
    communications: "ಸಂಪರ್ಕ ದಾಖಲೆಗಳು",
    logOut: "ಲಾಗ್ ಔಟ್",
    syllabus: "ಪಠ್ಯಕ್ರಮ ಮತ್ತು ಅಣಕು ಪರೀಕ್ಷೆಗಳು",
    analytics: "ವಿಶ್ಲೇಷಣೆ ಗ್ರಾಫ್‌ಗಳು",
    buyBooks: "ಪುಸ್ತಕಗಳನ್ನು ಖರೀದಿಸಿ",
    freeDonatedBooks: "ಉಚಿತ ದೇಣಿಗೆ ಪುಸ್ತಕಗಳು (₹0)",
    myBooksForSale: "ಮಾರಾಟಕ್ಕೆ ನನ್ನ ಪುಸ್ತಕಗಳು",
    myDonatedBooks: "ನನ್ನ ದಾನ ಪುಸ್ತಕಗಳು",
    sellOrDonate: "ಪುಸ್ತಕ ಮಾರಿ / ದಾನ ಮಾಡಿ",
    cart: "ಕಾರ್ಟ್",
    total: "ಒಟ್ಟು",
    addToCart: "ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ",
    studentId: "Student ID",
    unregisterExam: "ತೆಗೆದುಹಾಕಿ",
    enterMarks: "ಅಂಕಗಳನ್ನು ನಮೂದಿಸಿ",
    takeMockTest: "ಅಣಕು ಪರೀಕ್ಷೆ ತೆಗೆದುಕೊಳ್ಳಿ",
    preparingForExamIntro: "ಸ್ಪರ್ಧಾತ್ಮಕ ಪರೀಕ್ಷೆಗೆ ತಯಾರಿ ನಡೆಸುತ್ತಿದ್ದೀರಾ? ನಮಗೆ ಬಿಡಿ.",
  },
  bn: {
    exams: "পরীক্ষাসমূহ",
    myProgress: "আমার অগ্রগতি",
    marketplace: "মার্কেটপ্লেস",
    ordersTracking: "অর্ডার এবং ট্র্যাকিং",
    resources: "সম্পদ",
    community: "কমিউনিটি",
    studyPlanner: "স্টাডি প্ল্যানার",
    settings: "সেটিংস",
    adminDashboard: "অ্যাডমিন ড্যাশবোর্ড",
    deliveryDashboard: "ডেলিভারি ড্যাশবোর্ড",
    dashboard: "ড্যাশবোর্ড",
    manageExams: "পরীক্ষা পরিচালনা",
    manageResources: "সম্পদ পরিচালনা",
    manageProducts: "মার্কেটপ্লেস",
    users: "ব্যবহারকারী",
    orders: "অর্ডারসমূহ",
    returns: "রিটার্ন এবং দান",
    communications: "যোগাযোগের লগ",
    logOut: "লগ আউট",
    syllabus: "সিলেবাস এবং মক টেস্ট",
    analytics: "অগ্রগতি গ্রাফ",
    buyBooks: "বই কিনুন",
    freeDonatedBooks: "বিনামূল্যে দান করা বই (₹0)",
    myBooksForSale: "আমার বিক্রয়ের বই",
    myDonatedBooks: "আমার দান করা বই",
    sellOrDonate: "বই বিক্রি বা দান করুন",
    cart: "কার্ট",
    total: "মোট",
    addToCart: "কার্টে যোগ করুন",
    studentId: "Student ID",
    unregisterExam: "মুছে ফেলুন",
    enterMarks: "নম্বর লিখুন",
    takeMockTest: "মক টেস্ট দিন",
    preparingForExamIntro: "পরীক্ষার প্রস্তুতি নিচ্ছেন? আমাদের ওপর ছেড়ে দিন।",
  },
  mr: {
    exams: "परीक्षा",
    myProgress: "माझी प्रगती",
    marketplace: "मार्केटप्लेस",
    ordersTracking: "ऑर्डर्स आणि ट्रॅकिंग",
    resources: "संसाधने",
    community: "कम्युनिटी",
    studyPlanner: "अभ्यास नियोजक",
    settings: "सेटिंग्ज",
    adminDashboard: "प्रशासक डॅशबोर्ड",
    deliveryDashboard: "डिलिव्हरी डॅशबोर्ड",
    dashboard: "डॅशबोर्ड",
    manageExams: "परीक्षा व्यवस्थापन",
    manageResources: "संसाधन व्यवस्थापन",
    manageProducts: "मार्केटप्लेस",
    users: "वापरकर्ते",
    orders: "ऑर्डर्स",
    returns: "परतावा आणि देणगी",
    communications: "संवाद नोंदी",
    logOut: "लॉग आउट",
    syllabus: "अभ्यासक्रम आणि मॉक टेस्ट",
    analytics: "विश्लेषण आलेख",
    buyBooks: "पुस्तके खरेदी करा",
    freeDonatedBooks: "मोफत दान केलेली पुस्तके (₹0)",
    myBooksForSale: "माझी विक्रीसाठी पुस्तके",
    myDonatedBooks: "माझी दान केलेली पुस्तके",
    sellOrDonate: "पुस्तक विका किंवा दान करा",
    cart: "कार्ट",
    total: "एकूण",
    addToCart: "कार्टमध्ये जोडा",
    studentId: "Student ID",
    unregisterExam: "काढून टाका",
    enterMarks: "गुण प्रविष्ट करा",
    takeMockTest: "मॉक टेस्ट द्या",
    preparingForExamIntro: "स्पर्धा परीक्षेची तयारी करताय? आमच्यावर सोपवा.",
  },
};

function triggerGoogleTranslate(targetLang) {
  try {
    const isEn = !targetLang || targetLang === "en";
    const cookieVal = isEn ? "/en/en" : `/en/${targetLang}`;

    document.cookie = `googtrans=${cookieVal}; path=/;`;
    if (typeof window !== "undefined" && window.location.hostname) {
      document.cookie = `googtrans=${cookieVal}; path=/; domain=${window.location.hostname};`;
      const parts = window.location.hostname.split(".");
      if (parts.length > 1) {
        document.cookie = `googtrans=${cookieVal}; path=/; domain=.${parts.slice(-2).join(".")};`;
      }
    }

    const applyCombo = () => {
      const combo = document.querySelector(".goog-te-combo");
      if (combo) {
        if (combo.value !== targetLang) {
          combo.value = isEn ? "en" : targetLang;
          combo.dispatchEvent(new Event("change", { bubbles: true }));
        }
        return true;
      }
      return false;
    };

    if (!applyCombo()) {
      let attempts = 0;
      const interval = setInterval(() => {
        attempts++;
        if (applyCombo() || attempts > 20) {
          clearInterval(interval);
        }
      }, 200);
    }
  } catch (err) {
    console.warn("Google Translate trigger error:", err);
  }
}

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => localStorage.getItem("prepcycle_lang") || "en");

  useEffect(() => {
    if (lang && lang !== "en") {
      triggerGoogleTranslate(lang);
    }
  }, [lang]);

  const setLang = (nextLang) => {
    setLangState(nextLang);
    localStorage.setItem("prepcycle_lang", nextLang);
    triggerGoogleTranslate(nextLang);
  };

  const t = (key, defaultText) => {
    const dict = TRANSLATIONS[lang] || TRANSLATIONS.en;
    if (dict && dict[key]) return dict[key];
    if (defaultText && dict && dict[defaultText]) return dict[defaultText];
    if (TRANSLATIONS.en && TRANSLATIONS.en[key]) return TRANSLATIONS.en[key];
    return defaultText || key;
  };

  const localizeBookTitle = (title) => {
    if (!title || lang === "en") return title || "";

    // 1. Exact catalog match
    const langBooks = BOOK_TRANSLATIONS[lang];
    if (langBooks && langBooks[title]) return langBooks[title];

    // 2. Keyword & phrase token localization across subjects, editions, formats
    const vocab = VOCABULARY[lang];
    if (!vocab) return title;

    let localized = title;
    const sortedPhrases = Object.keys(vocab).sort((a, b) => b.length - a.length);
    for (const phrase of sortedPhrases) {
      const regex = new RegExp(`\\b${phrase}\\b`, "gi");
      localized = localized.replace(regex, vocab[phrase]);
    }
    return localized;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, localizeBookTitle, supportedLanguages: SUPPORTED_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    return {
      lang: "en",
      setLang: () => {},
      t: (_k, d) => d || _k,
      localizeBookTitle: (t) => t,
      supportedLanguages: SUPPORTED_LANGUAGES,
    };
  }
  return ctx;
}
