import Exam from "../models/Exam.js";
import Progress from "../models/Progress.js";
import { Note, Resource } from "../models/catalogModels.js";
import { buildRoadmapResponse } from "./progressController.js";

function localContext(notes, roadmaps) {
  const noteText = notes.map(n => `${n.title || "Note"}: ${n.content || ""}`).join("\n").slice(0, 12000);
  const progress = roadmaps.map(r => `${r.exam.name}: ${r.completion.percent}% complete; subjects: ${r.subjects.map(s => `${s.name} ${s.completion.percent}%`).join(", ")}`).join("\n");
  return { noteText, progress };
}

// Built-in intelligent study engine when external API keys are not present
function generateBuiltInResponse(message, context, notes, roadmaps) {
  const query = message.toLowerCase();

  // Progress and roadmap inquiries
  if (query.includes("progress") || query.includes("completion") || query.includes("status") || query.includes("track")) {
    if (context.progress) {
      return `📊 **Your PrepCycle Study Progress Overview**:\n\n${context.progress}\n\n💡 **Tip**: Focus on subjects with lower completion percentages first. High-weightage chapters give you the greatest return on time invested.`;
    }
    return `You haven't registered for any exams yet. Head over to **Exam Explorer** in the sidebar to register for GATE CSE, JEE, NEET, or UPSC and begin tracking your subject progress!`;
  }

  // Operating Systems
  if (query.includes("operating system") || query.includes("os") || query.includes("paging") || query.includes("deadlock") || query.includes("process") || query.includes("thread")) {
    return `💻 **Operating Systems Key Concepts**:\n\n` +
      `1. **Process Management**: A process is a program in execution. Thread is the basic unit of CPU utilization (shares code, data, files; has its own stack, registers, PC).\n` +
      `2. **CPU Scheduling**: FCFS, SJF (optimal average waiting time), Round Robin (preemptive with time quantum), Priority Scheduling.\n` +
      `3. **Paging & Virtual Memory**: Paging eliminates external fragmentation. Logical address is split into Page Number ($p$) and Page Offset ($d$). TLB (Translation Lookaside Buffer) caches page-table entries for faster translation.\n` +
      `4. **Deadlock**: Occurs when 4 conditions hold simultaneously: Mutual Exclusion, Hold and Wait, No Preemption, and Circular Wait. Handled via Prevention, Avoidance (Banker's Algorithm), or Detection & Recovery.\n\n` +
      `📚 **Recommended Reading**: *Operating System Concepts* by Silberschatz, Galvin & Gagne.`;
  }

  // Computer Networks
  if (query.includes("network") || query.includes("tcp") || query.includes("udp") || query.includes("osi") || query.includes("ip") || query.includes("routing")) {
    return `🌐 **Computer Networks Core Overview**:\n\n` +
      `1. **OSI vs TCP/IP Models**: Application, Presentation, Session, Transport, Network, Data Link, Physical.\n` +
      `2. **Transport Layer**: TCP is connection-oriented, reliable, with byte-stream service, flow control (sliding window), and congestion control (Slow Start, Congestion Avoidance). UDP is connectionless, unreliable, lightweight (DNS, VoIP, video streaming).\n` +
      `3. **Network Layer**: IPv4 (32-bit), IPv6 (128-bit), CIDR addressing, Subnetting. Routing algorithms: Distance Vector (Bellman-Ford) and Link State (Dijkstra - OSPF).\n` +
      `4. **Data Link Layer**: Framing, Error detection (CRC, Parity), Flow control (Stop-and-Wait, Go-Back-N, Selective Repeat).\n\n` +
      `📚 **Recommended Reading**: *Computer Networks* by Andrew S. Tanenbaum.`;
  }

  // Theory of Computation
  if (query.includes("automata") || query.includes("toc") || query.includes("dfa") || query.includes("nfa") || query.includes("turing") || query.includes("regular language") || query.includes("cfg")) {
    return `⚙️ **Theory of Computation Hierarchy (Chomsky Hierarchy)**:\n\n` +
      `1. **Type 3 - Regular Languages**: Recognized by Finite Automata (DFA/NFA) and generated by Regular Expressions. Closed under Union, Intersection, Complement, Concatenation, Kleene Star.\n` +
      `2. **Type 2 - Context-Free Languages**: Recognized by Non-deterministic Pushdown Automata (NPDA) and generated by CFGs. Closed under Union, Concatenation, Kleene Star (NOT closed under Intersection or Complement).\n` +
      `3. **Type 1 - Context-Sensitive**: Linear Bounded Automata.\n` +
      `4. **Type 0 - Recursively Enumerable**: Recognized by Turing Machines (Halting problem is undecidable).\n\n` +
      `📚 **Recommended Reading**: *Introduction to Automata Theory, Languages, and Computation* by Hopcroft, Motwani & Ullman.`;
  }

  // Data Structures & Algorithms
  if (query.includes("data structure") || query.includes("algorithm") || query.includes("sort") || query.includes("tree") || query.includes("graph") || query.includes("dp") || query.includes("dynamic programming")) {
    return `🌳 **Data Structures & Algorithms Essentials**:\n\n` +
      `1. **Asymptotic Complexities**: $O(1) < O(\\log n) < O(n) < O(n \\log n) < O(n^2) < O(2^n) < O(n!)$.\n` +
      `2. **Trees & Heaps**: Binary Search Tree (inorder is sorted), AVL Tree (height-balanced $|BF| \\le 1$), Binary Heap (Priority Queue: insertion and extract-min in $O(\\log n)$).\n` +
      `3. **Graph Traversals**: BFS (Queue, shortest path in unweighted graphs), DFS (Stack/Recursion, topological sort, connected components).\n` +
      `4. **Dynamic Programming**: Optimal Substructure + Overlapping Subproblems (Memoization vs Tabulation: 0/1 Knapsack, LCS, Matrix Chain Multiplication).\n\n` +
      `📚 **Recommended Reading**: *Introduction to Algorithms* by Cormen, Leiserson, Rivest & Stein (CLRS).`;
  }

  // GATE CSE preparation strategy
  if (query.includes("gate") || query.includes("strategy") || query.includes("study plan") || query.includes("how to prepare")) {
    return `🎯 **GATE CSE High-Scoring Preparation Strategy**:\n\n` +
      `1. **General Aptitude & Engineering Mathematics (28-30 Marks)**: These are scoring sections with high consistency. Revise discrete math (graph theory, combinatorics, logic) and calculus early.\n` +
      `2. **High-Yield Core Subjects**: Programming & DS (10-12 marks), Algorithms (6-8 marks), Operating Systems (8-10 marks), DBMS (7-9 marks), Computer Networks (8-10 marks), Theory of Computation (7-9 marks).\n` +
      `3. **Practice Standard Questions**: Solve previous 15 years' GATE questions (PYQs) at least twice.\n` +
      `4. **Take Subject Quizzes & Full Mock Tests**: Use PrepCycle's Quiz Generator to test your weak chapters and take full mock exams to calibrate your timing.`;
  }

  // Student notes reference
  if (query.includes("note") || query.includes("my notes")) {
    if (context.noteText) {
      return `📝 **Here are the key notes saved in your account**:\n\n${context.noteText.slice(0, 1000)}\n\n💡 Use the Notes tab under My Progress to add or edit your chapter notes.`;
    }
    return `You haven't created any study notes yet. You can create quick notes for any chapter in the **My Progress > Notes** section!`;
  }

  // Default comprehensive response
  return `Hello! I am your PrepCycle AI Study Assistant. 🦉\n\n` +
    `I can help you with:\n` +
    `• **Subject Explanations**: Concepts in Operating Systems, Computer Networks, Data Structures, Algorithms, DBMS, TOC, Engineering Math, and Aptitude.\n` +
    `• **Your Exam Progress**: Checking completed topics, remaining syllabus, and weak chapter analysis.\n` +
    `• **Study Planning**: Strategies for 7-day sprints, 30-day schedules, or 6-month master roadmaps.\n` +
    `• **Mock Tests & Quizzes**: Guidance on how to approach questions and analyze mistakes.\n\n` +
    `What subject or topic would you like to review today?`;
}

export async function chat(req, res) {
  const message = String(req.body?.message || "").trim();
  if (!message) return res.status(400).json({ message: "Message is required." });

  const [notes, progresses, resources] = await Promise.all([
    Note.find({ user: req.user._id }).sort({ updatedAt: -1 }).limit(20),
    Progress.find({ user: req.user._id }),
    Resource.find({ $or: [{ source: "catalog" }, { sharedBy: { $exists: true, $ne: null } }] }).sort({ createdAt: -1 }).limit(60),
  ]);

  const exams = await Exam.find({ slug: { $in: progresses.map(p => p.examSlug) } });
  const bySlug = Object.fromEntries(exams.map(e => [e.slug, e]));
  const roadmaps = progresses.filter(p => bySlug[p.examSlug]).map(p => buildRoadmapResponse(bySlug[p.examSlug], p));
  const context = localContext(notes, roadmaps);
  const resourceText = resources.map(r => `${r.title} — ${r.description || ""} — ${r.url || ""}`).join("\n").slice(0, 10000);

  // 1. Try Google Gemini API if configured
  const geminiKey = process.env.GEMINI_API_KEY;
  if (geminiKey) {
    try {
      const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${geminiKey}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [
            {
              role: "user",
              parts: [
                { text: `You are PrepCycle's intelligent educational study companion. Answer accurately, clearly, and encourage the student. Context:\nStudent Progress: ${context.progress || "None"}\nNotes: ${context.noteText || "None"}\nQuestion: ${message}` }
              ]
            }
          ]
        })
      });
      const data = await response.json();
      const reply = data?.candidates?.[0]?.content?.parts?.[0]?.text;
      if (reply) {
        return res.json({ reply, sources: [...notes.slice(0, 5).map(n => n.title), ...resources.slice(0, 5).map(r => r.title)] });
      }
    } catch {
      // Fall through to OpenAI or built-in engine
    }
  }

  // 2. Try OpenAI API if configured
  const openAiKey = process.env.OPENAI_API_KEY;
  if (openAiKey) {
    try {
      const model = process.env.OPENAI_MODEL || "gpt-4.1-mini";
      const payload = {
        model,
        messages: [
          { role: "system", content: "You are PrepCycle's educational companion. Answer clearly and accurately. Use the student's supplied notes and progress context when relevant. Do not invent details that are absent from the context. If a current exam fact is needed, tell the student to check the official exam page." },
          { role: "system", content: `Student progress:\n${context.progress || "None"}\n\nStudent notes:\n${context.noteText || "None"}\n\nPrepCycle resources:\n${resourceText || "None"}` },
          { role: "user", content: message },
        ],
        temperature: 0.2
      };
      const response = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: { Authorization: `Bearer ${openAiKey}`, "Content-Type": "application/json" },
        body: JSON.stringify(payload)
      });
      const data = await response.json();
      const reply = data.choices?.[0]?.message?.content;
      if (reply) {
        return res.json({ reply, sources: [...notes.slice(0, 5).map(n => n.title), ...resources.slice(0, 5).map(r => r.title)] });
      }
    } catch {
      // Fall through to built-in engine
    }
  }

  // 3. Fallback: Built-in intelligent educational study engine (never fails, always helpful)
  const reply = generateBuiltInResponse(message, context, notes, roadmaps);
  return res.json({
    reply,
    sources: [...notes.slice(0, 5).map(n => n.title), ...resources.slice(0, 5).map(r => r.title)],
  });
}
